export const styles = {
  Root: "h-full w-full p-3 min-h-0",
  Column: "h-full min-h-0 flex flex-col gap-3 relative",
  Top: "flex-1 min-h-0",
  KnobPanel: "min-h-0",

  BusCardAreaRoot: "h-full min-h-0 flex gap-3",
  BusCardAreaMain: "flex-1 min-w-0 min-h-0",
  BusCardButton: "h-full min-h-0 text-left relative overflow-hidden",
  BusCardInnerRow: "h-full min-h-0 flex items-center rounded-xl border border-dotted border-orange-400/80",
  BusCardLeft: "w-full min-w-0 min-h-0 flex flex-col justify-center",
  BusCardHeader: "absolute left-6 right-6 top-5 z-10 grid grid-cols-[1fr_auto] items-center gap-2",
  BusCardMapButton: "h-8 w-8 rounded-md border border-white/15 bg-white/10 hover:bg-white/20 active:bg-white/25 flex items-center justify-center cursor-grab active:cursor-grabbing",
  BusCardTitle: "text-[32px] leading-none font-semibold tracking-wide",
  BusCardModeBadgeBase: "inline-flex items-center px-2.5 py-1 rounded-full border text-[11px] leading-none",
  BusCardModeBadgeLinear: "bg-white/10 text-white/75 border-white/15",
  BusCardModeBadgeParallel: "bg-yellow-400/15 text-yellow-200 border-yellow-400/25",
  BusCardModeBadgeLcr: "bg-blue-400/15 text-blue-200 border-blue-400/25",
  BusCardRoutingSlot: "w-full min-h-0",
  BusCardTrackGrid: "w-full min-h-[262px] flex flex-col justify-center gap-12 px-10",
  BusCardSignalRow: "relative w-full rounded-xl border border-white/10",
  BusCardSignalLabel: "pointer-events-none absolute left-2 top-2 z-30 rounded-md border border-white/10 bg-[#111519]/95 px-2 py-0.5 text-[11px] font-semibold tracking-[0.12em] text-white/75 shadow-[0_2px_8px_rgba(0,0,0,0.55)]",
  BusCardSignalLine: "absolute inset-x-0 top-1/2 h-[2px] -translate-y-1/2 rounded-full bg-gradient-to-r from-emerald-400/35 via-emerald-300/90 to-emerald-400/70 shadow-[0_0_10px_rgba(52,211,153,0.35)]",
  BusCardSignalStart: "absolute left-0 top-1/2 h-2.5 w-2.5 -translate-x-1/2 -translate-y-1/2 rounded-full border border-emerald-200/70 bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,0.65)]",
  BusCardSignalArrow: "absolute right-0 top-1/2 h-0 w-0 translate-x-1/2 -translate-y-1/2 border-y-[7px] border-l-[12px] border-y-transparent border-l-emerald-300 drop-shadow-[0_0_5px_rgba(110,231,183,0.7)]",
  BusCardSignalSlots: "relative z-10 m-1 grid grid-cols-[repeat(9,10.5%)] justify-center gap-0",
  BusCardSignalSlot: "relative aspect-[1.05/1] cursor-pointer touch-manipulation rounded-lg border border-transparent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300/90",
  BusCardSignalSlotDragTarget: "before:pointer-events-none before:absolute before:left-1/2 before:top-1/2 before:z-10 before:h-[84px] before:w-[94px] before:-translate-x-1/2 before:-translate-y-1/2 before:rounded-xl before:border before:border-cyan-200/30 before:bg-cyan-300/[0.07] before:shadow-[0_0_12px_rgba(103,232,249,0.16)] before:content-['']",
  BusCardPlacedModule: "group/fxblock absolute inset-0 z-20 flex cursor-grab items-center justify-center overflow-hidden rounded-lg touch-none active:cursor-grabbing focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/80",
  BusCardPlacedModuleScale: "pointer-events-none h-[74px] w-[84px] transition-transform duration-75 group-active/fxblock:scale-[0.97] group-active/fxblock:brightness-90",
  BusCardDragGhost: "pointer-events-none fixed z-[9999] h-[74px] w-[84px]",
  
  // RoutingWell
  RoutingWellRoot: "h-full min-h-0 p-3 flex flex-col gap-2",
  RoutingWellHeader: "flex items-center justify-between",
  RoutingWellTitle: "text-[11px] font-semibold tracking-wide text-white/70",
  RoutingWellFooter: "pt-1 text-[10px] text-white/35",
  ModeBadge: "text-[10px] px-2 py-0.5 rounded-full bg-white/10 border border-white/10 text-white/70",
  LanePillBase: "flex items-center justify-between px-2 py-1 rounded-lg border min-w-0",
  LanePillOn: "bg-white/10 border-white/15",
  LanePillOff: "bg-black/20 border-white/5 opacity-45",
  LanePillActiveRing: "ring-1 ring-green-400/40",
  LaneMapButton: "h-5 w-5 rounded border border-white/15 bg-white/10 hover:bg-white/20 active:bg-white/25 flex items-center justify-center cursor-grab active:cursor-grabbing",
  LaneStatePillBase: "text-[10px] px-2 py-0.5 rounded-full border",
  LaneStateOn: "bg-green-400/10 text-green-200 border-green-400/20",
  LaneStateOff: "bg-white/5 text-white/40 border-white/10",

  // PluginList (if you end up using it in Perform)
  PluginInset: "h-full min-h-0 p-2",
  PluginHeader: "flex items-center justify-between px-1 pb-2",
  PluginTitle: "text-[11px] font-semibold tracking-wide text-white/70",
  PluginCount: "text-[10px] text-white/35",
  PluginRows: "flex flex-col gap-1 min-h-0",
  PluginRowBase: "flex items-center gap-2 px-2 py-1.5 rounded-lg",
  PluginRowActive: "bg-white/10 border border-white/10",
  PluginRowIdle: "bg-white/0",
  PluginIndex: "w-5 text-[11px] opacity-60 tabular-nums",
  PluginName: "text-[12px] font-semibold leading-tight truncate",
  PluginVendor: "text-[11px] opacity-55 leading-tight truncate",
  PluginStateOn: "bg-green-400/10 text-green-200 border-green-400/20",
  PluginStateOff: "bg-white/5 text-white/40 border-white/10",
  
};

export const KNOB_STRIP_H = 185;
